server:
  port: 9998
  servlet:
    context-path: /FILE


logging:
  level:
    org.springframework.web: ERROR
  file: /usr/local/filelog/log.txt


eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://0.0.0.0:7101/eureka/,http://127.0.0.1:7102/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于microservice-product:8001
    prefer-ip-address: true  #访问路径就会显示成IP地址



windows_logging:
  file: d:/log/file_logs.txt
windows_server:
  filepath: d:/fileServer/

linux_logging:
  file: /mnt/data/files_log/
linux_server:
  filepath: /mnt/data/files/



spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1024MB
  application:
    name: FILE

#  datasource:
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: ttd4x76
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create-drop
#    show-sql: false
#
#logging:
#  level:
#    org.boot.uploader.*: debug

prop:
  upload-folder: ./files
